### ISSUE TITLE
Question about the implementation of Non-local block

### ISSUE THREAD

**Issue by szx503045266** [Tushar-N/pytorch-resnet3d#4]
Hi. I didn't see the code below in other implemetation version of non-local block and I don't quite understand its usage.
`theta_phi_sc = theta_phi * (self.dim_inner**-.5)`
https://github.com/Tushar-N/pytorch-resnet3d/blob/e997fc6a4a632502460aece5e83e0bd2fd6206d9/models/resnet.py#L114
Could you please explain what it is used for? Thanks a lot.

**Comment by Tushar-N** [comment]
This is the scale operation as described in Sec 3.2.1 of [this](https://arxiv.org/pdf/1706.03762.pdf) paper. It isn't described in the original NL paper, but it shows up in the official authors implementation [here](https://github.com/facebookresearch/video-nonlocal-net/blob/master/lib/models/nonlocal_helper.py#L86):
```
theta_phi_sc = model.Scale(theta_phi, theta_phi, scale=dim_inner**-.5)
```
 `cfg.NONLOCAL.USE_SCALE` is set to `True` in the config that was used to generate the pretrained models as seen in the training [logs](https://dl.fbaipublicfiles.com/video-nonlocal/i3d_nonlocal_32x2_IN_pretrain_400k.log).

[This](https://github.com/facebookresearch/video-nonlocal-net/issues/65#issuecomment-512818934) comment on the original repo explains some other differences from common implementations. This repo just converts the c2 model to pytorch (rather than train from scratch), so the model definitions had to be consistent.

**Comment by szx503045266** [comment]
Thanks for your quick and detailed reply! It helps me a lot.
